# Generated by Django 4.2.3 on 2023-10-07 13:45

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default=' ', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
