# Generated by Django 4.2.3 on 2023-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
