# Generated by Django 4.2.3 on 2023-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Order Inquiry', 'Order Inquiry'), ('Product Feedback', 'Product Feedback'), ('Account Issue', 'Account Issue'), ('General Inquiry', 'General Inquiry'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
