# Generated by Django 4.2.3 on 2023-10-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='subject',
            field=models.CharField(choices=[('Order Inquiry', 'Order Inquiry'), ('Product Feedback', 'Product Feedback'), ('Account Issue', 'Account Issue'), ('General Inquiry', 'General Inquiry'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
