# Generated by Django 4.2.3 on 2023-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_value',
            field=models.CharField(choices=[('1.0', '★☆☆☆☆ (1/5)'), ('2.0', '★★☆☆☆ (2/5)'), ('3.0', '★★★☆☆ (3/5)'), ('4.0', '★★★★☆ (4/5)'), ('5.0', '★★★★★ (5/5)')], max_length=3),
        ),
    ]
